# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.13
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: "sudo apt-get update"
      - run: "sudo apt-get update -y"
      - run: "sudo apt-get install build-essential"
      - run: "sudo apt-get install git"
      - run: "git clone https://github.com/etivvenkata/vigilant-giggle.git"
      - run: "cd vigilant-giggle"
      - run: "g++ giggle.c -o giggle"
      - run: "./giggle"
      - run: "sudo mkdir -p /giggle/DEBIAN "
      - run: "sudo touch /giggle/DEBIAN/control"
      - run: "chmod 777 /giggle/DEBIAN/control"
      - run: "sudo echo Package: giggle >> /giggle/DEBIAN/control "
    

workflows:
  # Name the workflow "welcome"



